from mc.graph import Graph
from mc.node import Node, IndexNode
from typing import Dict
import mc.operators as ops
import numpy as np
from mc.utils import cpp_type, CodeWriter
import os

class CodeGen(CodeWriter):
    name_dict: Dict[str, str]
    def __init__(self, graph: Graph):
        super().__init__()
        self.graph = graph
        self.name_dict = {}

    def node_name(self, node: Node):
        if node.name not in self.name_dict:
            node_name = node.name
            node_name = node_name.replace('/', '_')
            node_name = node_name.replace('::', '_')
            node_name = node_name.replace('.', '_')
            if not node_name.replace('_', '').isalnum() or '__' in node_name:
                raise ValueError(f'Node name {node_name} is not valid')
            self.name_dict[node.name] = node_name
        return self.name_dict[node.name]

    def tensor_name(self, inode: IndexNode):
        return f'{self.node_name(inode.node)}__{inode.index}'

    def write_helper_code(self):
        code_template = r'''// generated by MCCompiler
#include <cstdio>
#include <cstdlib>
#include <string>
#include <fstream>

#define checkCudaErrors(stmt) {                                 \
    cudaError_t err = stmt;                            \
    if (err != cudaSuccess) {                          \
    fprintf(stderr, "%s in file %s, function %s, line %i: %04d %s\n", #stmt, __FILE__, __FUNCTION__, __LINE__, err, cudaGetErrorString(err)); \
    exit(1); \
    }                                                  \
}

#define checkBlasErrors(stmt) { \
    cublasStatus_t err = stmt; \
    if (err != CUBLAS_STATUS_SUCCESS) {                          \
    fprintf(stderr, "%s in file %s, function %s, line %i: %04d %s\n", #stmt, __FILE__, __FUNCTION__, __LINE__, err, cublasGetErrorString(err)); \
    exit(1); \
    } \
}

void load_tensor(std::string f_name, void* buffer, size_t size) {
    std::ifstream f(f_name.c_str(), std::ios::in | std::ios::binary);
    if (!f.is_open()) {
        fprintf(stderr, "Cannot open file %s", f_name.c_str());
        exit(1);
    }
    f.read((char*)buffer, size);
    f.close();
}
    '''
        self.write(code_template)

    def write_init_code(self):
        node_list = self.graph.topological_sort()
        self.wl('char* cuda_buffer;')
        for node in node_list:
            if not isinstance(node, ops.Input):
                for i in range(len(node.output_types)):
                    self.wl(f'{cpp_type(node.output_types[i].dtype)}* {self.tensor_name(IndexNode(node, i))};')
        self.wl('')
        buffer_size = 0
        for node in node_list:
            if not isinstance(node, ops.Input):
                for i in range(len(node.output_types)):
                    buffer_size += node.output_types[i].size() * node.output_types[i].dtype.itemsize
        buffer_ptr = 0
        self.wl('void init()')
        self.block_start()
        self.wl(f'checkCudaErrors(cudaMalloc(&cuda_buffer, {buffer_size}));')
        for node in node_list:
            if not isinstance(node, ops.Input):
                for i in range(len(node.output_types)):
                    self.wl(f'{self.tensor_name(IndexNode(node, i))} = ({cpp_type(node.output_types[i].dtype)}*)(cuda_buffer + {buffer_ptr}); /* {node.output_types[i].shape} * {node.output_types[i].dtype.itemsize} */')
                    buffer_ptr += node.output_types[i].size() * node.output_types[i].dtype.itemsize
        for node in node_list:
            if isinstance(node, ops.Constant):
                self.wl(f'load_tensor("{self.tensor_name(IndexNode(node, 0))}.bin", {self.tensor_name(IndexNode(node, 0))}, {node.output_types[0].size() * node.output_types[0].dtype.itemsize});')
        assert buffer_ptr == buffer_size
        self.block_end()
        self.wl('')


    def write_kernels(self):
        node_list = self.graph.topological_sort()
        for node in node_list:
            if isinstance(node, (ops.Input, ops.Constant, ops.Output)):
                continue
            params = [f'{cpp_type(t.dtype)}* input{i}' for i, t in enumerate(node.input_types)]
            params += [f'{cpp_type(t.dtype)}* output{i}' for i, t in enumerate(node.output_types)]
            func_sig =  f"void kernel_{self.node_name(node)}({', '.join(params)})"
            self.wl(f'// {node}')
            self.wl(f'// {node.input_types}')
            self.wl(f'// {node.output_types}')
            self.write(node.get_cuda_code(func_sig))
            self.wl('')
        
        run_params = []
        for node in self.graph.inputs:
            assert isinstance(node, ops.Input)
            run_params.append(f'{cpp_type(node.output_types[0].dtype)}* {self.tensor_name(IndexNode(node, 0))}')
        for i, node in enumerate(self.graph.outputs):
            assert isinstance(node, ops.Output)
            run_params.append(f'{cpp_type(node.input_types[0].dtype)}* &output{i}')
        
        self.wl(f'void run({", ".join(run_params)})')
        self.block_start()
        for node in node_list:
            if isinstance(node, (ops.Input, ops.Constant, ops.Output)):
                continue
            params = [self.tensor_name(input_node) for input_node in node.input_nodes]
            params += [self.tensor_name(IndexNode(node, i)) for i in range(len(node.output_types))]
            self.wl(f'kernel_{self.node_name(node)}({", ".join(params)});')
        
        for i, node in enumerate(self.graph.outputs):
            assert isinstance(node, ops.Output)
            assert len(node.input_nodes) == 1
            self.wl(f'output{i} = {self.tensor_name(node.input_nodes[0])};')
        self.block_end()
        self.wl('')


    def write_test_code(self):
        self.wl('int main()')
        self.block_start()
        self.wl('init();')
        for i, node in enumerate(self.graph.inputs):
            assert isinstance(node, ops.Input)
            self.wl(f'{cpp_type(node.output_types[0].dtype)}* {self.tensor_name(IndexNode(node, 0))}; // input{i}')
            self.wl(f'load_tensor("{self.tensor_name(IndexNode(node, 0))}.bin", {self.tensor_name(IndexNode(node, 0))}, {node.output_types[0].size() * node.output_types[0].dtype.itemsize});')
        for i, node in enumerate(self.graph.outputs):
            assert isinstance(node, ops.Output)
            self.wl(f'{cpp_type(node.input_types[0].dtype)}* {self.tensor_name(node.input_nodes[0])}; // output{i}')
        self.wl('run(' + ', '.join([self.tensor_name(IndexNode(node, 0)) for node in self.graph.inputs] + [self.tensor_name(node.input_nodes[0]) for node in self.graph.outputs]) + ');')
        self.wl('return 0;')
        self.block_end()

    def write_code(self):
        self.write_helper_code()
        self.write_init_code()
        self.write_kernels()
        self.write_test_code()


def codegen(graph):
    writer = CodeGen(graph)
    writer.write_code()
    print(writer.code_str)
    with open('tmp/test.cu', 'w') as f:
        f.write(writer.code_str)
    os.system('nvcc -std=c++11 -arch=sm_70 -O3 -o tmp/test tmp/test.cu')

    # TODO: save constants
